'use server'

import { createClient } from '@/lib/supabase/server'
export type { BrandedReportData } from '@/lib/utils/expense-pdf'
import type { ExpenseWithRelations } from '@/types/finance'

// ── Report types ──────────────────────────────────────────────────────────────

export type ReportType =
  | 'monthly'
  | 'department'
  | 'employee'
  | 'vendor'
  | 'category'
  | 'tax'
  | 'booking'
  | 'travel'
  | 'outstanding'

export interface ReportFilter {
  reportType: ReportType
  startDate?: string
  endDate?: string
  department?: string
  employee?: string
  vendor?: string
  category?: string
}


// ── Generate branded report data ──────────────────────────────────────────────


export async function generateReportData(filter: ReportFilter): Promise<BrandedReportData> {
  const supabase = await createClient()
  const user = (await supabase.auth.getUser()).data.user

  let query = supabase
    .from('expenses')
    .select(`
      *,
      vendors!fk_expenses_vendor(name),
      profiles!expenses_recorded_by_fkey(first_name, last_name),
      bookings!expenses_booking_id_fkey(booking_reference)
    `)
    .order('expense_date', { ascending: false })

  if (filter.startDate) query = query.gte('expense_date', filter.startDate)
  if (filter.endDate) query = query.lte('expense_date', filter.endDate)
  if (filter.department) query = query.eq('department', filter.department)
  if (filter.category) query = query.ilike('category', `%${filter.category}%`)
  if (filter.vendor) {
    // vendor filtering via join is done in-memory after fetch
  }

  const { data, error } = await query
  if (error) throw new Error(`Failed to generate report: ${error.message}`)

  const rows = (data || []).map((row: Record<string, unknown>) => {
    const vendor = row.vendors as { name?: string } | null
    const profile = row.profiles as { first_name?: string; last_name?: string } | null
    const booking = row.bookings as { booking_reference?: string } | null
    return {
      ...row,
      vendor_name: vendor?.name ?? null,
      employee_name: profile ? `${profile.first_name || ''} ${profile.last_name || ''}`.trim() : null,
      booking_reference: booking?.booking_reference ?? null,
    } as ExpenseWithRelations
  })

  const totalAmount = rows.reduce((s, e) => s + (e.amount || 0), 0)
  const totalRecords = rows.length

  // Category frequency
  const catCount: Record<string, number> = {}
  rows.forEach((e) => { if (e.category) catCount[e.category] = (catCount[e.category] || 0) + 1 })
  const topCategory = Object.entries(catCount).sort((a, b) => b[1] - a[1])[0]?.[0] ?? '-'

  // Department frequency
  const deptCount: Record<string, number> = {}
  rows.forEach((e) => { if (e.department) deptCount[e.department] = (deptCount[e.department] || 0) + 1 })
  const topDepartment = Object.entries(deptCount).sort((a, b) => b[1] - a[1])[0]?.[0] ?? '-'

  const now = new Date()
  const period = filter.startDate && filter.endDate
    ? `${filter.startDate} to ${filter.endDate}`
    : `All time as of ${now.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`

  const { data: profileData } = await supabase
    .from('profiles')
    .select('first_name, last_name')
    .eq('id', user?.id ?? '')
    .single()
  const generatedBy = profileData
    ? `${profileData.first_name || ''} ${profileData.last_name || ''}`.trim() || user?.email || 'System'
    : user?.email || 'System'

  const titleMap: Record<ReportType, string> = {
    monthly: 'Monthly Expense Report',
    department: 'Department Expense Report',
    employee: 'Employee Expense Report',
    vendor: 'Vendor Expense Report',
    category: 'Category Expense Report',
    tax: 'Tax Report',
    booking: 'Booking Expense Report',
    travel: 'Travel Expense Report',
    outstanding: 'Outstanding Payments Report',
  }

  const summary =
    `This report covers ${totalRecords} expense record${totalRecords !== 1 ? 's' : ''} ` +
    `totaling ${new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(totalAmount)}. ` +
    `The highest-volume category was ${topCategory} and the most active department was ${topDepartment}. ` +
    `Period: ${period}. Generated by ${generatedBy} on ${now.toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}.`

  return {
    title: titleMap[filter.reportType],
    period,
    generatedBy,
    generatedAt: now.toISOString(),
    summary,
    totalAmount,
    totalRecords,
    topCategory,
    topDepartment,
    expenses: rows,
  }
}

// ── CSV export ────────────────────────────────────────────────────────────────

export async function exportExpensesCSV(expenses: ExpenseWithRelations[]): Promise<string> {
  const headers = [
    'Expense Number', 'Date', 'Employee', 'Department', 'Vendor', 'Category',
    'Description', 'Amount', 'Tax', 'Currency', 'Payment Method',
    'Status', 'Approval Status', 'Notes',
  ]
  const rows = expenses.map((e) => [
    e.expense_number ?? '',
    e.expense_date,
    e.employee_name ?? '',
    e.department ?? '',
    e.vendor_name ?? '',
    e.category,
    e.description,
    e.amount.toString(),
    (e.tax ?? 0).toString(),
    e.currency ?? 'USD',
    e.payment_method ?? '',
    e.status ?? '',
    e.approval_status ?? '',
    e.notes ?? '',
  ])

  const BOM = '\uFEFF' // UTF-8 BOM for Excel compat
  const csv = BOM + [headers, ...rows]
    .map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(','))
    .join('\n')

  return csv
}

