import type { Booking, BookingTraveler, BookingChecklist, BookingTimelineEvent, BookingNote } from '@/types'

// Mock bookings data
export const MOCK_BOOKINGS: Booking[] = [
  {
    id: '1',
    booking_reference: 'BK-001',
    customer_id: 'CUST-001',
    customer_name: 'Wanderlust Tours Ltd',
    destination: 'Iceland - Northern Lights Adventure',
    trip_start_date: '2024-12-15',
    trip_end_date: '2024-12-22',
    status: 'confirmed',
    total_cost: 45000,
    currency: 'USD',
    num_travelers: 8,
    booking_type: 'group_tour',
    special_requests: 'Prefer accommodations with hot springs access',
    assigned_to: 'sales@omniatravel.com',
    assigned_to_name: 'Sarah Johnson',
    created_at: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'sales@omniatravel.com',
    notes: 'VIP customer. Requires executive briefing before departure.',
  },
  {
    id: '2',
    booking_reference: 'BK-002',
    customer_id: 'CUST-002',
    customer_name: 'Swiss Alps Expeditions',
    destination: 'Switzerland - Alpine Explorer',
    trip_start_date: '2024-12-28',
    trip_end_date: '2025-01-04',
    status: 'pending',
    total_cost: 32000,
    currency: 'USD',
    num_travelers: 12,
    booking_type: 'group_tour',
    special_requests: 'All participants must have advanced skiing experience',
    assigned_to: 'ops@omniatravel.com',
    assigned_to_name: 'Operations Team',
    created_at: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    created_by: 'sales@omniatravel.com',
    notes: 'Waiting for final payment confirmation',
  },
  {
    id: '3',
    booking_reference: 'BK-003',
    customer_id: 'CUST-003',
    customer_name: 'Mediterranean Cruises',
    destination: 'Greece - Island Hopping',
    trip_start_date: '2025-01-10',
    trip_end_date: '2025-01-18',
    status: 'in_progress',
    total_cost: 28500,
    currency: 'USD',
    num_travelers: 6,
    booking_type: 'cruise',
    special_requests: 'Cabin upgrade requested for honeymoon couple',
    assigned_to: 'ops@omniatravel.com',
    assigned_to_name: 'Operations Team',
    created_at: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    updated_at: new Date().toISOString(),
    created_by: 'sales@omniatravel.com',
    notes: 'Documentation in final review phase',
  },
]

// Mock travelers
export const MOCK_TRAVELERS: Record<string, BookingTraveler[]> = {
  '1': [
    {
      id: 't1',
      booking_id: '1',
      first_name: 'John',
      last_name: 'Smith',
      email: 'john@example.com',
      phone: '+1-555-0123',
      date_of_birth: '1985-03-15',
      passport_number: 'US123456789',
      passport_expiry: '2027-03-15',
      nationality: 'United States',
      room_type: 'double',
      meal_plan: 'full_board',
      special_requirements: null,
      created_at: new Date().toISOString(),
    },
    {
      id: 't2',
      booking_id: '1',
      first_name: 'Jane',
      last_name: 'Smith',
      email: 'jane@example.com',
      phone: '+1-555-0124',
      date_of_birth: '1988-07-22',
      passport_number: 'US987654321',
      passport_expiry: '2026-07-22',
      nationality: 'United States',
      room_type: 'double',
      meal_plan: 'full_board',
      special_requirements: 'Vegetarian meals',
      created_at: new Date().toISOString(),
    },
  ],
  '2': [
    {
      id: 't3',
      booking_id: '2',
      first_name: 'Pierre',
      last_name: 'Dubois',
      email: 'pierre@example.fr',
      phone: '+33-1-2345-6789',
      date_of_birth: '1980-05-10',
      passport_number: 'FR9876543210',
      passport_expiry: '2025-05-10',
      nationality: 'France',
      room_type: 'single',
      meal_plan: 'half_board',
      special_requirements: null,
      created_at: new Date().toISOString(),
    },
  ],
}

// Mock checklist
export const MOCK_CHECKLIST: Record<string, BookingChecklist[]> = {
  '1': [
    {
      id: 'c1',
      booking_id: '1',
      item_name: 'Confirm flight bookings',
      category: 'flights',
      is_completed: true,
      assigned_to: 'ops@omniatravel.com',
      due_date: '2024-11-15',
      notes: 'All flights confirmed with Icelandair',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'c2',
      booking_id: '1',
      item_name: 'Hotel reservations',
      category: 'accommodation',
      is_completed: true,
      assigned_to: 'ops@omniatravel.com',
      due_date: '2024-11-20',
      notes: '8 rooms confirmed at The Retreat Hotel',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'c3',
      booking_id: '1',
      item_name: 'Arrange vehicle rentals',
      category: 'transport',
      is_completed: false,
      assigned_to: 'ops@omniatravel.com',
      due_date: '2024-11-25',
      notes: null,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  '2': [
    {
      id: 'c4',
      booking_id: '2',
      item_name: 'Collect skiing certifications',
      category: 'documentation',
      is_completed: false,
      assigned_to: 'ops@omniatravel.com',
      due_date: '2024-12-15',
      notes: 'Need proof of advanced skiing experience',
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
}

// Mock timeline
export const MOCK_TIMELINE: Record<string, BookingTimelineEvent[]> = {
  '1': [
    {
      id: 'e1',
      booking_id: '1',
      event_type: 'booking_confirmed',
      description: 'Booking confirmed by customer',
      event_date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
      created_by: 'sales@omniatravel.com',
      related_to: null,
      created_at: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    },
    {
      id: 'e2',
      booking_id: '1',
      event_type: 'payment_received',
      description: '50% deposit received - $22,500',
      event_date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
      created_by: 'finance@omniatravel.com',
      related_to: null,
      created_at: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
    },
  ],
}

// Mock notes
export const MOCK_NOTES: Record<string, BookingNote[]> = {
  '1': [
    {
      id: 'n1',
      booking_id: '1',
      note_text: 'Customer requested specific guide - Miguel has been assigned',
      created_by: 'ops@omniatravel.com',
      note_type: 'internal',
      is_private: true,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: 'n2',
      booking_id: '1',
      note_text: 'Insurance documents sent to customer',
      created_by: 'sales@omniatravel.com',
      note_type: 'customer',
      is_private: false,
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
}
