// Shared utility — no server/client directive
// Can be imported by both server and client components

export interface BrandedReportData {
  title: string
  period: string
  generatedBy: string
  generatedAt: string
  summary: string
  totalAmount: number
  totalRecords: number
  topCategory: string
  topDepartment: string
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  expenses: any[]
}

export function buildPDFCoverPage(report: BrandedReportData): string {
  const fmt = (n: number) =>
    new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(n)

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    body { font-family: 'Segoe UI', sans-serif; margin: 0; padding: 0; background: #f9fafb; }
    .cover { background: linear-gradient(135deg, #0f2340 0%, #0d9488 100%); min-height: 100vh; display: flex; flex-direction: column; align-items: center; justify-content: center; color: white; padding: 60px; }
    .logo { font-size: 36px; font-weight: 800; letter-spacing: -1px; margin-bottom: 8px; }
    .logo span { color: #5eead4; }
    .tagline { font-size: 14px; opacity: 0.7; margin-bottom: 60px; }
    .report-title { font-size: 28px; font-weight: 700; margin-bottom: 12px; text-align: center; }
    .period { font-size: 16px; opacity: 0.85; margin-bottom: 48px; }
    .stats { display: grid; grid-template-columns: 1fr 1fr 1fr; gap: 24px; margin-bottom: 48px; width: 100%; max-width: 600px; }
    .stat { background: rgba(255,255,255,0.12); border-radius: 12px; padding: 20px; text-align: center; }
    .stat-value { font-size: 24px; font-weight: 700; }
    .stat-label { font-size: 12px; opacity: 0.75; margin-top: 4px; }
    .summary { background: rgba(255,255,255,0.08); border-radius: 12px; padding: 24px; max-width: 700px; font-size: 14px; line-height: 1.6; opacity: 0.9; margin-bottom: 40px; }
    .meta { font-size: 12px; opacity: 0.6; }
  </style>
</head>
<body>
  <div class="cover">
    <div class="logo">Omnia<span>Travel</span></div>
    <div class="tagline">Enterprise ERP System — Finance Module</div>
    <div class="report-title">${report.title}</div>
    <div class="period">${report.period}</div>
    <div class="stats">
      <div class="stat">
        <div class="stat-value">${fmt(report.totalAmount)}</div>
        <div class="stat-label">Total Amount</div>
      </div>
      <div class="stat">
        <div class="stat-value">${report.totalRecords}</div>
        <div class="stat-label">Total Records</div>
      </div>
      <div class="stat">
        <div class="stat-value">${report.topCategory}</div>
        <div class="stat-label">Top Category</div>
      </div>
    </div>
    <div class="summary">${report.summary}</div>
    <div class="meta">Generated by ${report.generatedBy} &bull; ${new Date(report.generatedAt).toLocaleString()}</div>
  </div>
</body>
</html>`
}

// ── Invoice PDF builders ──────────────────────────────────────────────────────

export interface InvoiceCoverPageData {
  title: string
  period: string
  generatedBy: string
  generatedAt: string
  summary: string
  totalRevenue: number
  totalInvoices: number
  collectionRate: number
  outstandingBalance: number
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  invoices: any[]
}

export function buildInvoiceCoverPage(data: InvoiceCoverPageData): string {
  const fmt = (n: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(n)

  const tableRows = data.invoices.slice(0, 100).map((inv: Record<string, unknown>) =>
    `<tr>
      <td>${inv.invoice_number as string ?? ''}</td>
      <td>${inv.customer_name as string ?? inv.customer_id as string ?? ''}</td>
      <td>${inv.issued_date as string ?? ''}</td>
      <td>${inv.due_date as string ?? ''}</td>
      <td>${inv.currency as string ?? 'USD'}</td>
      <td style="text-align:right">${fmt((inv.total_amount as number) ?? 0)}</td>
      <td><span style="padding:2px 8px;border-radius:4px;font-size:10px;background:${statusColor(inv.status as string)};color:white">${inv.status as string ?? ''}</span></td>
    </tr>`
  ).join('')

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', sans-serif; background: #f9fafb; color: #1e293b; }
    .cover { background: linear-gradient(135deg, #0f2340 0%, #1d4ed8 100%); padding: 60px; color: white; display: flex; flex-direction: column; align-items: center; min-height: 40vh; }
    .logo { font-size: 32px; font-weight: 800; letter-spacing: -1px; margin-bottom: 6px; }
    .logo span { color: #93c5fd; }
    .tagline { font-size: 13px; opacity: 0.7; margin-bottom: 40px; }
    .report-title { font-size: 26px; font-weight: 700; margin-bottom: 8px; text-align: center; }
    .period { font-size: 15px; opacity: 0.85; margin-bottom: 36px; }
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 20px; width: 100%; max-width: 800px; margin-bottom: 36px; }
    .stat { background: rgba(255,255,255,0.12); border-radius: 10px; padding: 18px; text-align: center; }
    .stat-value { font-size: 22px; font-weight: 700; }
    .stat-label { font-size: 11px; opacity: 0.75; margin-top: 4px; }
    .summary-box { background: rgba(255,255,255,0.08); border-radius: 10px; padding: 20px; max-width: 700px; font-size: 13px; line-height: 1.7; opacity: 0.92; }
    .meta { font-size: 11px; opacity: 0.55; margin-top: 20px; }
    .content { padding: 40px; }
    table { width: 100%; border-collapse: collapse; font-size: 12px; }
    th { background: #1e3a5f; color: white; padding: 10px 12px; text-align: left; font-size: 11px; letter-spacing: 0.03em; }
    td { padding: 9px 12px; border-bottom: 1px solid #e2e8f0; }
    tr:hover td { background: #f0f9ff; }
    .section-title { font-size: 16px; font-weight: 700; color: #1e3a5f; margin: 32px 0 16px; border-left: 4px solid #1d4ed8; padding-left: 12px; }
  </style>
</head>
<body>
  <div class="cover">
    <div class="logo">Omnia<span>Travel</span></div>
    <div class="tagline">Enterprise ERP System — Finance &amp; Revenue Module</div>
    <div class="report-title">${data.title}</div>
    <div class="period">${data.period}</div>
    <div class="stats">
      <div class="stat"><div class="stat-value">${fmt(data.totalRevenue)}</div><div class="stat-label">Total Revenue</div></div>
      <div class="stat"><div class="stat-value">${data.totalInvoices}</div><div class="stat-label">Total Invoices</div></div>
      <div class="stat"><div class="stat-value">${data.collectionRate.toFixed(1)}%</div><div class="stat-label">Collection Rate</div></div>
      <div class="stat"><div class="stat-value">${fmt(data.outstandingBalance)}</div><div class="stat-label">Outstanding</div></div>
    </div>
    <div class="summary-box">${data.summary}</div>
    <div class="meta">Generated by ${data.generatedBy} &bull; ${new Date(data.generatedAt).toLocaleString()}</div>
  </div>
  <div class="content">
    <div class="section-title">Invoice Details — ${data.period}</div>
    <table>
      <thead><tr><th>Invoice #</th><th>Customer</th><th>Issued</th><th>Due</th><th>Currency</th><th style="text-align:right">Total</th><th>Status</th></tr></thead>
      <tbody>${tableRows}</tbody>
    </table>
  </div>
</body>
</html>`
}

function statusColor(status: string): string {
  const map: Record<string, string> = {
    draft: '#64748b', sent: '#3b82f6', paid: '#0d9488',
    partially_paid: '#8b5cf6', overdue: '#ef4444', cancelled: '#6b7280',
  }
  return map[status] || '#64748b'
}

export interface BoardReportPageData {
  title: string
  period: string
  generatedBy: string
  generatedAt: string
  summary: string
  kpis: Array<{ label: string; value: string; change: string }>
  healthScore: number
  healthGrade: string
  recommendations: string[]
}

export function buildBoardReportPage(data: BoardReportPageData): string {
  const gradeColor = data.healthGrade === 'A' ? '#0d9488' : data.healthGrade === 'B' ? '#3b82f6' : data.healthGrade === 'C' ? '#f59e0b' : data.healthGrade === 'D' ? '#f97316' : '#ef4444'

  const kpiRows = data.kpis.map(k =>
    `<tr><td style="font-weight:600;color:#1e3a5f">${k.label}</td><td style="font-size:18px;font-weight:700">${k.value}</td><td style="color:${k.change.startsWith('+') ? '#0d9488' : k.change.startsWith('-') ? '#ef4444' : '#64748b'};font-weight:600">${k.change}</td></tr>`
  ).join('')

  const recItems = data.recommendations.map(r => `<li style="margin-bottom:8px;color:#374151">${r}</li>`).join('')

  return `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Segoe UI', sans-serif; background: #f8fafc; color: #1e293b; }
    .cover { background: linear-gradient(135deg, #0f2340 0%, #1d4ed8 100%); padding: 70px 60px; color: white; text-align: center; }
    .logo { font-size: 40px; font-weight: 800; letter-spacing: -1px; margin-bottom: 8px; }
    .logo span { color: #93c5fd; }
    .tagline { font-size: 14px; opacity: 0.65; margin-bottom: 48px; }
    .report-title { font-size: 32px; font-weight: 700; margin-bottom: 10px; }
    .period { font-size: 18px; opacity: 0.85; margin-bottom: 16px; }
    .meta { font-size: 12px; opacity: 0.55; }
    .content { padding: 48px 60px; max-width: 900px; margin: 0 auto; }
    .section { margin-bottom: 40px; }
    .section-title { font-size: 18px; font-weight: 700; color: #1e3a5f; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #e2e8f0; }
    .summary-text { font-size: 16px; line-height: 1.8; color: #374151; background: #f0f9ff; border-left: 4px solid #1d4ed8; padding: 20px 24px; border-radius: 0 8px 8px 0; }
    .kpi-table { width: 100%; border-collapse: collapse; }
    .kpi-table td { padding: 14px 16px; border-bottom: 1px solid #e2e8f0; font-size: 15px; }
    .health-box { display: flex; align-items: center; gap: 32px; background: white; border-radius: 12px; padding: 28px; border: 1px solid #e2e8f0; box-shadow: 0 2px 8px rgba(0,0,0,0.04); }
    .gauge { font-size: 64px; font-weight: 800; color: ${gradeColor}; }
    .grade { font-size: 24px; font-weight: 700; color: ${gradeColor}; margin-top: 4px; }
    ul { list-style: disc; padding-left: 20px; }
  </style>
</head>
<body>
  <div class="cover">
    <div class="logo">Omnia<span>Travel</span></div>
    <div class="tagline">CONFIDENTIAL — FOR BOARD USE ONLY</div>
    <div class="report-title">${data.title}</div>
    <div class="period">${data.period}</div>
    <div class="meta">Generated by ${data.generatedBy} &bull; ${new Date(data.generatedAt).toLocaleString()}</div>
  </div>
  <div class="content">
    <div class="section">
      <div class="section-title">Executive Summary</div>
      <div class="summary-text">${data.summary}</div>
    </div>
    <div class="section">
      <div class="section-title">Key Performance Indicators</div>
      <table class="kpi-table">
        <tbody>${kpiRows}</tbody>
      </table>
    </div>
    <div class="section">
      <div class="section-title">Invoice Health Score</div>
      <div class="health-box">
        <div>
          <div class="gauge">${data.healthScore}</div>
          <div class="grade">Grade ${data.healthGrade}</div>
          <div style="font-size:13px;color:#64748b;margin-top:4px">out of 100</div>
        </div>
        <div style="flex:1">
          <div style="font-weight:600;color:#1e3a5f;margin-bottom:12px">Recommendations</div>
          <ul>${recItems}</ul>
        </div>
      </div>
    </div>
  </div>
</body>
</html>`
}

